apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "ratings"
  title: "ratings"
  description: "Ratings API"
  annotations:
    backstage.io/spectral-ruleset-url: https://raw.githubusercontent.com/bookinfo/spectral-rules/main/ruleset.yaml
  links:
    - url: https://registry-apicurio-registry.apps.cluster-9h552.dynamic.redhatworkshops.io/ui/artifacts/com.redhat.demo.bookinfo/ratings/versions/latest
      title: Apicurio Registry
      icon: web
    - url: https://microcks-microcks.apps.cluster-9h552.dynamic.redhatworkshops.io/#/services?name=ratings
      title: Microcks
    - url: https://microcks-microcks.apps.cluster-9h552.dynamic.redhatworkshops.io/rest/ratings/v1
      title: Mock
      icon: web
spec:
  type: openapi
  system: system:default/bookinfo
  owner: group:default/backstage-admins
  lifecycle: production
  definition:
    $openapi: https://github.com/contract-first-idp-test/bookinfo-ratings-api/blob/main/specification.yaml