openapi: 3.0.3
info:
  title: ratings
  description: |-
    Ratings API
  version: 'v1'
servers:
  - url: "http://localhost:8080"
  - url: "https://microcks-microcks.apps.cluster-9h552.dynamic.redhatworkshops.io/rest/ratings/v1"
paths: {}
